- frontend/models/ResetPasswordForm.php
No need validation `user` model for reset action. Validation occurs in the `this` model.
> Turn off validation  for reset password

- environments/index.php
- init
This allows you to specify files that should only be copied if the target doesn't exist yet and be skipped if it does.
You can use this functionality to not overwrite files that you manually edited directly in the folder (eg. if you wish to keep your database passwords completely out of your source control and fill them in after deploy on the server). This will prevent you having to do this each time the regular configuration changes and you have to run ./init again
> Added "skipFiles" functionality to the init command.

- frontend/models/SignupForm.php
Without that rule trying to sign up will cause database exception or email right trim depends on db server settings when email length > 255 and <320 (covered by email validator) characters.
> Additional "email" rule for signup form model

- common/models/LoginForm.php
Its implemented for caching user model only (to not make double query), its not part of public api.
> Changed \common\models\LoginForm::getUser from public to private

- common/models/LoginForm.php
@cebe, @samdark Guys, sorry for boring, last time we changed it from public to private and this was right by reasons posted inside previous PR around it. But it should be protected, because this method may be interested inside children classes.
> Changed \common\models\LoginForm::getUser from private to protected

- tests/README.md
Before:
```
tests/codeception/common$ codecept build                                                                                
Building Actor classes for suites: unit
tests\codeception\common\UnitTester includes modules: 
PHP Fatal error:  Call to undefined method Codeception\Lib\Generator\Actor::getNumMethods() in /Users/bazilio/.composer/vendor/codeception/codeception/src/Codeception/Command/Build.php on line 74
PHP Stack trace:
PHP   1. {main}() /Users/bazilio/.composer/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /Users/bazilio/.composer/vendor/codeception/codeception/codecept:27
PHP   3. …
```
> Upgrade codeception in tests/README.md

- composer.json
| Fixed issues  | 
I think we can make yii2 installation process a lot easier, if the initiation will be done automatically after composer dependencies are installed. Today, as a newbie in Yii I spent a lot of time figuring out why my application is not working, that was because in was not initialized after dependencies have been installed.
However, automatical execution of this command after `composer install` will not be harmful, since it will not overwrite the existent configuration.
> Add post install application initialization

- environments/dev/backend/web/index.php
- environments/dev/frontend/web/index.php
- environments/prod/backend/web/index.php
- environments/prod/frontend/web/index.php
Eliminated inconsistency of `index.php`:
```PHP
$application = new common\components\WebApp($config);
$application->run();
```
versus `index-test.php`:
```PHP
(new yii\web\Application($config))->run();
```
> Removed `$application` variable for consistence with `index-test.php`

- backend/views/layouts/main.php
- backend/web/css/site.css
- frontend/views/layouts/main.php
- frontend/web/css/site.css
Fixes the logout button by increasing it's size to be the same as other
links in the navbar.
Originally the logout button size is slightly smaller in the non-collapsed navbar
as it is made to be the same size using padding on the form. It is also
smaller in the collapsed navbar where it doesn't take up 100% of the
width unlike other links.
> Increase logout button size

- frontend/tests/acceptance/HomeCest.php
| Fixed issues  | 
Acceptance test HomeCest fails for me on step `$I->see('This is the About page.');`. This PR fixes it in same manner as in https://github.com/yiisoft/yii2-app-basic/blob/master/tests/acceptance/HomeCest.php.
> Fix for acceptance test.

- docs/guide/start-installation.md
In 2.2, access control based on client hostname, IP address, and other characteristics of client requests was done using the directives Order, Allow, Deny, and Satisfy.
In 2.4, such access control is done in the same way as other authorization checks, using the new module mod_authz_host.
> apache acl (2.2, 2.4)

- composer.json
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
> Fix composer deprecated msg.

- vagrant/provision/once-as-root.sh
| Breaks BC?    | yes
| Fixed issues  | #282 
Remove remote host on xdebug configuration and add remote connect back
> Remove remote host on xdebug configuration

- backend/views/layouts/main.php
- frontend/views/layouts/main.php
When not set in `config/web.php` the value of `Yii::$app->name` is `'My Company'` already.
Same as in https://github.com/yiisoft/yii2-app-basic/pull/141
> Application name instead of string literal in the navbar

- docs/guide/start-testing.md
There are no versions of what components to use so if you follow the instructions it will use the latest ones. Currently the latest ones don't work together and the acceptance tests fail. I spent 2 days trawling through forums and github bug reports to figure it all out!
| Fixed issues  | none
> Instructions don't work with latest code versions

- docs/guide/start-installation.md
I've lost ONE HOUR trying to connect the new installation to the db because I was editing the wrong main-local.php. I was editing the file located in the path C:\MAMP\htdocs\yii2-app-advanced\common\config instead of C:\MAMP\htdocs\yii2-app-advanced\yii-application\common\config
> Specify location of main-local.php to edit

- composer.json
| Fixed issues  | #378
phpunit 7.2 included some BC breaks so this PR simply prevents the installation of that version.
> Fix #378 restrict phpunit to prevent BC break

- init
minor change to support dash separated params in init file.
> support dash separated params in php init

- init
Issue #379 
| Tests pass?   | there are no tests
| Fixed issues  | Now the script is making a strict comparison of the environment argument, preventing the execution when that argument is not passed properly and avoiding the generation of dev and prod directories into the project root.
> #379 - Adjustment to prevent the execution when args are not passed properly

- backend/Dockerfile
- docker-compose.yml
- docs/guide/start-installation.md
- frontend/Dockerfile
| Tests pass?   | there are none
| Fixed issues  | #214, #244 
Related: https://github.com/yiisoft/yii2-docker/issues/28#issuecomment-371098356, https://github.com/yiisoft/yii2-app-advanced/pull/250
> added minimal Docker setup

- backend/Dockerfile
- frontend/Dockerfile
| Tests pass?   | ?
| Fixed issues  | #409 
Linking locations seem to be somehow unreliable, so this PR updates the document root in the image build process.
> replace document root, fixes #409

- requirements.php
It is useful in build/deploy/integration procedures in order to stop build process if requirements don’t met.
> Make requirements checker return error if there were failed checks

- requirements.php
Same as in https://github.com/yiisoft/yii2-app-basic/pull/201
> Old array syntax in requirement checker (could be run in PHP prior to 5.4)

- backend/web/css/site.css
This makes sure that the nowrap is only applied on the last `td` of each row on grid-view, so that action icons dont wrap.
It also ensures sorting icons (up/down arrows) are not wrapped.
> fix nowrap messing with all gridview cells

- composer.json
- frontend/tests/unit/models/ContactFormTest.php
- frontend/tests/unit/models/ResendVerificationEmailFormTest.php
- frontend/tests/unit/models/SignupFormTest.php
Update codeception/verify dependency to 1.1.0 and use `stringContainsString()` assertion instead of `contains()`, because `assertContains` with string haystacks is deprecated in PHPUnit 8
| Fixed issues  | https://github.com/Codeception/Codeception/pull/5571
Currently 3 tests fail with PHPUnit 8, this change fixes yii2 build in Codeception and allows you to extend supported versions of `codeception/base` up to 3.x and PHPUnit up to 8.x when you are ready for that.
I have no idea why `codeception/base` is restricted to 2.4.x and `phpunit/phpunit` to `~6.5.5`.
> Update codeception/verify to 1.1.0

- .travis.yml
- composer.json
I released a version of codeception/verify which runs on PHP 5.6
| Fixed issues  | #440
> Run tests on PHP 5.6

- composer.json
Codeception 4.0 is modular, so installing only necessary modules and their dependencies reduces the size of vendor directory.
> Use modular Codeception 4.0

- composer.json
This change allows to use PHPUnit 7 and 8 with Yii2-app-advanced template.
This template does not use PHPUnit directly, 
it uses Codeception and it is responsibility of Codeception to manage compatibility with PHPUnit.
Also there is no such restriction in basic app.
| Fixed issues  | N/A
> Remove version restriction for PHPUnit

- docs/guide/topic-link-backend-frontend.md
On custom named url managers, the `class` element is required. You will get a `Invalid Configuration` exception without it!
| Tests pass?   | yes (its a doc edit lol)
| Fixed issues  | #466
> Add missing class to urlManagerFrontend

- docs/guide/topic-link-backend-frontend.md
As requested, here is a PR for going into more detail on the docs guide "topic-link-backend-frontend".
Let me know if you need anything changed. Feel free to modify it... or toss it out :)
@samdark and I discussed this in #466 
He mentioned using "params", however they are not available yet in the config array. (I tried first just to be sure)
The extra steps are necessary to limit "hard coding" the domain/urls. This method utilizes Yii2's environments to dynamically change the domain name based on the environment. Aliases are then created so the generation is only done once. Not that the functions do anything resource intensive, but aliases are cleaner and easier for the end user to remember in case they want to reference those URLs anywhere else later via …
> Add more detail to docs guide: topic-link-backend-frontend.md

- Vagrantfile
- vagrant/provision/once-as-root.sh
- vagrant/provision/provision.awk
Vagrant's virtual machine IP is not in the `allowedIPs` lists for "Gii" and "debug toolbar".
By default, Yii2's Vagrant CIDR notation is 192.168.83.137/24, so we convert it to 192.168.83.* then add to each of the `allowedIPs` lists in the "environments/dev/***end**/config/main-local.php" files.
| Breaks BC?    | yes
> Enh: Add virtual machine IP to the Yii2 Advanced "allowedIPs"

- Vagrantfile
If `required_plugins` were not installed, the Vagrant any call process will stop after the installation of each of them.
_It's good that there only two required plugins - three launches, and we will reach the goal!_ 😅
Now it's fixed and Vagrant startup process doesn't stop.
| Breaks BC?    | yes
> Enh: Vagrant plugin[s] installation nonstop

- .github/workflows/build.yml
The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. 
For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Fix set-env github actions

- composer.json
Fix a small annoyance in PHPStorm where the generated files from codeception are not under the accurate namespace:
This adds the `_support` folder into the relevant namespace
> Fix namespaces in IDE for codeception

- backend/Dockerfile
- frontend/Dockerfile
Change Docker image versions to yii2-php:8.1-apache
| Fixed issues  | #533
> Dockerfiles: Changed to yii2-php:8.1-apache

- .github/workflows/build.yml
| Fixed issues  | Updated GH Action
Upgrade the GitHub checkout version from v2 to the latest v5, as v2 is outdated.
Latest release
https://github.com/actions/checkout/releases/tag/v5.0.0
> Change: updated checkout version in GH from v2 to v5
