yiisoft/yii2-app-advanced

tests/codeception/common/_support/FixtureHelper.php

Cleaned up some of the comments

Clarify some comments in FixtureHelper [ci skip]

---

tests/codeception/config/config.php

Like here https://github.com/yiisoft/yii2-app-basic/pull/9

Set en language in test

---

tests/codeception/common/_support/FixtureHelper.php

Add InitDbFixture to FixtureHelper

---

tests/codeception/common/unit/models/LoginFormTest.php
tests/codeception/frontend/unit/models/PasswordResetRequestFormTest.php
tests/codeception/frontend/unit/models/ResetPasswordFormTest.php
tests/codeception/frontend/unit/models/SignupFormTest.php

Fix problem "The closing brace MUST be on the next line after the body"

fix closing brace on the next line after the body

---

backend/views/layouts/main.php
backend/views/site/error.php
backend/views/site/index.php
backend/views/site/login.php
frontend/views/layouts/main.php
frontend/views/site/about.php
frontend/views/site/contact.php
frontend/views/site/error.php
frontend/views/site/index.php
frontend/views/site/login.php
frontend/views/site/requestPasswordResetToken.php
frontend/views/site/resetPassword.php
frontend/views/site/signup.php

https://github.com/yiisoft/yii2/blob/master/docs/internals/view-code-style.md

Format views to the View Code Style

---

environments/dev/frontend/config/main-local.php

As https://github.com/yiisoft/yii2-app-advanced/commit/67663dfe1cef4c3b7aab522f436924a2bd059238

More novice friendly config for gii/debug

---

tests/codeception/common/_support/FixtureHelper.php
tests/codeception/frontend/functional/SignupCest.php

Fix for https://github.com/yiisoft/yii2/issues/5575

Make functional and acceptance tests able to use custom fixtures

---

frontend/web/css/site.css

1. Fixed indentation.
2. Removed extra closing curly bracket.
3. Added linebreak for consistence.

Fixed errors in frontend site.css

---

backend/web/css/site.css

Similar to #101, but for backend.

Fixed errors in backend site.css

---

backend/web/css/site.css
common/config/bootstrap.php
frontend/web/css/site.css

[Yii2 issue #8771](https://github.com/yiisoft/yii2/issues/8771)
[Issue #65](https://github.com/yiisoft/yii2-app-advanced/issues/65)

Add nowrap only for ActionColumn

---

backend/views/site/login.php
frontend/views/site/contact.php
frontend/views/site/login.php
frontend/views/site/requestPasswordResetToken.php
frontend/views/site/resetPassword.php
frontend/views/site/signup.php

Autofocus on the first form field

---

backend/assets/AppAsset.php
frontend/assets/AppAsset.php

Asset files has many changes by times and copyright needs to pull all time by BSD. Can you remove it?
@qiangxue :gift_heart:

:copyright: Remove notice

---

docs/guide/start-installation.md

As I was confused by the steps described, I proposed to make them a little more obvious and portable (especially on windows).

Doc: Make preparing application steps clearer

---

backend/web/css/site.css
frontend/web/css/site.css

| Fixed issues  | #139 
Fixes the padding issue for the logout button when the navbar is collapsed.

Bug #139: Fix logout button padding bug

---

docs/guide-ja/start-installation.md

docs/guide-ja/start-installation.md updated [ci skip]

---

frontend/models/PasswordResetRequestForm.php
frontend/models/SignupForm.php

| Fixed issues  | 152
Fix for https://github.com/yiisoft/yii2-app-advanced/issues/152.

Shorter trim validator notation

---

docs/guide-ja/structure-directories.md
docs/guide-ja/topic-link-backend-frontend.md
docs/guide/topic-link-backend-frontend.md

Japanese translation of the documentation updated.

docs/guide-ja updated [ci skip]

---

tests/codeception/common/_pages/LoginPage.php
tests/codeception/frontend/_pages/ContactPage.php
tests/codeception/frontend/_pages/SignupPage.php

formName added in Tests

---

frontend/views/site/contact.php

Method textArea does not exist in the ActiveField

---

common/widgets/Alert.php
tests/codeception/backend/acceptance/LoginCept.php
tests/codeception/backend/functional/LoginCept.php
tests/codeception/frontend/_pages/SignupPage.php
tests/codeception/frontend/acceptance/AboutCept.php
tests/codeception/frontend/acceptance/ContactCept.php
tests/codeception/frontend/acceptance/HomeCept.php
tests/codeception/frontend/acceptance/LoginCept.php
tests/codeception/frontend/functional/AboutCept.php
tests/codeception/frontend/functional/ContactCept.php
tests/codeception/frontend/functional/HomeCept.php
tests/codeception/frontend/functional/LoginCept.php

corrected namespace

---

tests/codeception/common/_pages/LoginPage.php
tests/codeception/frontend/_pages/AboutPage.php
tests/codeception/frontend/_pages/ContactPage.php
tests/codeception/frontend/acceptance/SignupCest.php
tests/codeception/frontend/functional/SignupCest.php

corrected the namespace in the comments

---

frontend/models/PasswordResetRequestForm.php

Save user only if password_reset_token is being changed

---

docs/guide/topic-shared-hosting.md

docs/guide/topic-shared-hosting.md broken link removed [ci skip]

---

docs/guide/topic-shared-hosting.md

Fix a typo

---

backend/web/css/site.css

Fix code style issues

---

docs/guide/start-testing.md

typo fixed [ci skip]

---

docs/guide/start-testing.md

Adjusted testing documentation to reflect changes of PR #203

---

backend/web/css/site.css
frontend/web/css/site.css

| Fixed issues  | 
Removes text outline and underline when logout button is active.

Logout button style changes

---

frontend/controllers/SiteController.php
frontend/models/PasswordResetRequestForm.php

This PR fixes some messages for end users. It's a very minor issue, but I found it nonetheless annoying :-)

Fix some end-user messages

---

requirements.php

Fix error in Linux `ln` command: parameters rearranged

---

Vagrantfile

small spelling change

---

console/config/main.php

| Fixed issues  | yiisoft/yii2#13272

Fixes default namespace for FixtureController

---

common/config/bootstrap.php

collapse dirname(...)

---

Vagrantfile
vagrant/nginx/app.conf
vagrant/provision/always-as-root.sh
vagrant/provision/once-as-root.sh

* Ubuntu 16.04 Xenial
* PHP 7.0
* MySQL 5.7

Closes #233: Upgrade vagrant stack

---

vagrant/provision/once-as-vagrant.sh

Removed global Codeception installing.

Removed Vargant deprecated code

---

backend/views/layouts/main.php
frontend/views/layouts/main.php

This patch is to improve compatibility with Internet Explorer per Twitter Bootstrap's Bootlint.
https://github.com/twbs/bootlint/wiki/W002

Add meta tag for X-UA-Compatible

---

docs/guide-fr/start-comparison.md
docs/guide-fr/start-composer.md
docs/guide-fr/start-installation.md
docs/guide-fr/start-testing.md

adding for files start-*.md to French guide [skip ci]

---

docs/guide-fr/structure-applications.md
docs/guide-fr/structure-directories.md
docs/guide-fr/structure-environments.md
docs/guide-fr/structure-path-aliases.md

adding 4 files (structure-*.md) to French guide [skip ci]

---

docs/guide-fr/topic-adding-more-apps.md
docs/guide-fr/topic-link-backend-frontend.md
docs/guide-fr/topic-shared-hosting.md

adding 3 files (topic-*.md) to French guide [skip ci]

---

vagrant/provision/once-as-vagrant.sh

Fixed Vagrant migrations setup

---

composer.json
docs/guide-es/start-composer.md
docs/guide-fr/start-composer.md
docs/guide-ja/start-composer.md
docs/guide-pt-BR/start-composer.md
docs/guide-zh-CN/start-composer.md
docs/guide/start-composer.md

Removing post-install composer script

---

backend/config/test.php
frontend/config/test.php

set UrlManager::$showScriptName=true in tests

---

backend/web/.gitignore
environments/dev/backend/web/robots.txt
environments/dev/frontend/web/robots.txt
environments/prod/backend/web/robots.txt
environments/prod/frontend/web/robots.txt
frontend/web/.gitignore

Added robots.txt for exclude from index backend application on both environments and frontend when dev.

Add robots.txt to environment configurations

---

composer.lock
vagrant/provision/once-as-root.sh

| New feature?  | Yes
| Fixed issues  | None
Add xdebug configuration on vagrant to debug code on development

configure xdebug on vagrant

---

backend/tests/functional/LoginCest.php
common/tests/unit/models/LoginFormTest.php
frontend/tests/functional/LoginCest.php

| Tests pass?   | 
| Fixed issues  | Part of https://github.com/yiisoft/yii2/pull/14381

Use _fixtures for loading fixtures in tests

---

Vagrantfile

Updated Vagrant box

---

Vagrantfile

Revert "Updated Vagrant box"

---

backend/config/main.php
backend/tests/_bootstrap.php
common/tests/_bootstrap.php
console/config/main.php
environments/dev/backend/config/test-local.php
environments/dev/backend/web/index-test.php
environments/dev/backend/web/index.php
environments/dev/common/config/test-local.php
environments/dev/frontend/config/test-local.php
environments/dev/frontend/web/index-test.php
environments/dev/frontend/web/index.php
environments/dev/yii
environments/dev/yii_test
environments/prod/backend/web/index.php
environments/prod/frontend/web/index.php
environments/prod/yii
frontend/config/main.php
frontend/tests/_bootstrap.php
init
requirements.php

| Fixed issues  | https://github.com/yiisoft/yii2-app-basic/issues/123

Use `require` `require_once` as a statement, not a function

---

common/models/LoginForm.php

Fixed else statement feature

---

composer.json

up yiisoft/yii2-swiftmailer

---

backend/views/layouts/main.php
frontend/views/layouts/main.php

Use application name instead of string literal in the copyright footer line

---

docs/guide/start-installation.md

Removing duplication in instruction about installing advanced template

Update start-installation.md — removing duplication

---

.travis.yml

Added explicit imagick installation

---

Vagrantfile
docs/guide/start-installation.md
vagrant/config/vagrant-local.example.yml

| Tests pass?   | -
| Fixed issues  | #281

Vagrant fixes

---

.bowerrc

@see https://github.com/yiisoft/yii2-app-basic/pull/147

fix bowerrc

---

backend/controllers/SiteController.php
frontend/controllers/SiteController.php

| Tests pass?   | -
similar to [PR158](https://github.com/yiisoft/yii2-app-basic/pull/158)

password set to empty string

---

backend/controllers/SiteController.php
frontend/controllers/SiteController.php

codestyle add0ca7

---

backend/codeception.yml
backend/tests/functional.suite.yml
backend/tests/unit.suite.yml
common/codeception.yml
common/tests/unit.suite.yml
frontend/codeception.yml
frontend/tests/acceptance.suite.yml.example
frontend/tests/functional.suite.yml
frontend/tests/unit.suite.yml

| Is bugfix?    | yes (codeception config for codeception code generator)
| Breaks BC?    | no (but we must change another similar config manually - yii2-app-advanced can't have all of 9 config, only 5+1 example)
| Fixed issues  | related https://github.com/Codeception/Codeception/issues/4687

Add suite_namespace to configs

---

environments/dev/yii
environments/dev/yii_test
environments/dev/yii_test.bat
environments/prod/yii
init
init.bat
yii.bat

Removed unnecessary copyright comments.

---

vagrant/provision/always-as-root.sh
vagrant/provision/common.sh
vagrant/provision/once-as-root.sh
vagrant/provision/once-as-vagrant.sh

Moving shared vagrant provision code to common.sh

---

composer.json

See https://github.com/yiisoft/yii2-app-basic/issues/149
| Tests pass?   | probably
| Fixed issues  | https://github.com/yiisoft/yii2-app-basic/issues/149

Disable composer-asset-plugin if it's installed

---

common/config/test.php

Added cookie validation key to tests config

---

frontend/tests/functional/LoginCest.php

PHPDocs and style [skip ci]

---

init

skip initialization when directory does not exists

---

backend/codeception.yml
backend/config/.gitignore
common/codeception.yml
common/config/.gitignore
environments/dev/backend/config/codeception-local.php
environments/dev/common/config/codeception-local.php
environments/dev/common/config/test-local.php
environments/dev/frontend/config/codeception-local.php
environments/index.php
frontend/codeception.yml
frontend/config/.gitignore

| Is bugfix?    | no (test fix)
| Fixed issues  | #346

Cookie validation common

---

composer.json

| Breaks BC?    | -
| Tests pass?   | -

Fix PHPUnit version on Vagrant

---

.gitignore
backend/web/.gitignore
frontend/web/.gitignore

fixes #324
| Tests pass?   | n/a
| Fixed issues  |  #324

remove publicly accessable .gitignore files

---

environments/index.php

setWritable 'console/runtime'

---

.travis.yml

So.. php 7.3 is comming...
| Tests pass?   | --

Update test config .travis.yml for php 7.2 

---

docs/guide-ja/start-installation.md

| Tests pass?   | --
| Fixed issues  | --

docs/guide-ja/start-installation.md typo fixed [ci skip]

---

requirements.php

The basic template has this block, I think it is a good idea to have it in the advanced template as well.

Search for framework path in requirements.php

---

composer.json

| Breaks BC?    | ???
| Tests pass?   | ???

master: Update composer.json to use Yii2 Debug & Gii v2.1.0

---

console/migrations/m190124_110200_add_verification_token_column_to_user_table.php

| Is bugfix?        | yes
| Breaks BC?     | no
| Tests pass?    | no
| Fixed issues  | Fix default migration with 'tablePrefix'

Fix default migration with 'tablePrefix'

---

docs/guide/start-installation.md

| Fixed issues  | Fix grammatical error

Fix grammatical error

---

common/models/User.php

Add comment to generateEmailVerificationToken method

---

docs/guide-ja/start-testing.md

| Tests pass?   | --
| Fixed issues  | guide-ja updated

docs/guide-ja/start-testing.md update [ci skip]

---

backend/codeception.yml
common/codeception.yml
frontend/codeception.yml

| Is bugfix?    | Future Proofing
Changed codeception.yml files to move the bootstrap setting out of the Settings section.

Minor  changes to remove deprecation messages

---

docs/guide/start-installation.md

Issue #457 is about placing 'php' within the docker command
Issue #458 is about inverting docker commands
| New feature?  |no
| Breaks BC?    |no
| Fixed issues  | 457 and 458

Update start-installation.md in regards to issues #457 and #458

---

.travis.yml
frontend/models/SignupForm.php

increases default minimum password length to 12

---

docs/guide-ja/topic-link-backend-frontend.md

Japanese Guide Updated [ci skip]

---

backend/controllers/SiteController.php
backend/views/layouts/blank.php
backend/views/site/login.php
backend/web/css/site.css

Add minimal center layout and login form

---

docs/guide-es/start-installation.md
docs/guide-fr/start-installation.md
docs/guide-ja/start-installation.md
docs/guide-pl/start-installation.md
docs/guide-pt-BR/start-installation.md
docs/guide-zh-CN/start-installation.md
docs/guide/start-installation.md
init

Looks like #215 
Remove files from other environments not exists in current environment
| Fixed issues  | #215

Removing files from other env which not exists in current env

---

backend/views/layouts/blank.php

Add tag div

---

.github/workflows/build.yml

Remove unsed code coverage.

---

backend/Dockerfile
frontend/Dockerfile

Change version in docker container source to 7.4

---

composer.json

gii update

---

Vagrantfile
vagrant/nginx/app.conf
vagrant/provision/always-as-root.sh
vagrant/provision/once-as-root.sh

Fix #502: Update php and ubuntu version in vagrant stack

---

backend/views/layouts/blank.php
backend/views/layouts/main.php
backend/views/site/error.php
backend/views/site/index.php
backend/views/site/login.php
common/mail/emailVerify-html.php
common/mail/emailVerify-text.php
common/mail/layouts/html.php
common/mail/passwordResetToken-html.php
common/mail/passwordResetToken-text.php
frontend/views/layouts/main.php
frontend/views/site/about.php
frontend/views/site/contact.php
frontend/views/site/error.php
frontend/views/site/index.php
frontend/views/site/login.php
frontend/views/site/requestPasswordResetToken.php
frontend/views/site/resendVerificationEmail.php
frontend/views/site/resetPassword.php
frontend/views/site/signup.php

```
@var ["Type"] [element_name] [<description>]
```
https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/var.html

Syntax @var

---

composer.json

replace codeception 5.0.0-alpha2 with codeception 5.0.0

replace codeception 5.0.0-alpha2 with codeception 5.0.0

---

composer.json

removed dev-codecept5 from composer and replaced with latest releast 1.1.6

---

.gitignore

| Fixed issues  | [529](https://github.com/yiisoft/yii2-app-advanced/issues/529)

remove composer.lock from .gitignore

---

composer.json

Use https urls for yiiframework.com

---

docs/guide-zh-CN/start-installation.md

Fixed docs/guide-zh-CN/start-installation.md

---

composer.json
docs/guide-es/start-composer.md
docs/guide-fr/start-composer.md
docs/guide-ja/start-composer.md
docs/guide-pl/start-composer.md
docs/guide-pt-BR/start-composer.md
docs/guide-zh-CN/start-composer.md
docs/guide/start-composer.md

update irc link

---

backend/views/site/index.php

| Fixed issues  | resolve https://github.com/yiisoft/yii2-app-advanced/issues/543

update backend folder links

---

console/migrations/m130524_201442_init.php

| Fixed issues  | resolve https://github.com/yiisoft/yii2-app-advanced/issues/545

update console folder link

---

frontend/views/site/index.php

| Fixed issues  | resolve https://github.com/yiisoft/yii2-app-advanced/issues/549

update frontend folder links

---

README.md
requirements.php

| Fixed issues  | resolve https://github.com/yiisoft/yii2-app-advanced/issues/551

update root folder links
